# Generated by Django 4.1.3 on 2022-11-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_product',
        ),
    ]
